"""Fish shell support utilities for Volume Monitor."""
# Volume Monitor — https://github.com/Tech127x/volume-monitor
# Copyright (c) 2025 Tech127x

import logging
import os
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


def detect_shell() -> str:
    """Detect the current user's shell."""
    shell_path = os.environ.get("SHELL", "")
    if not shell_path:
        # Try to detect from /etc/passwd
        try:
            import pwd
            shell_path = pwd.getpwuid(os.getuid()).pw_shell
        except Exception:
            pass

    return Path(shell_path).name if shell_path else "unknown"


def is_fish_shell() -> bool:
    """Check if user is running Fish shell."""
    return detect_shell() == "fish" or "FISH_VERSION" in os.environ


def get_shell_config_file() -> Optional[Path]:
    """Get the appropriate shell config file path."""
    home = Path.home()
    shell = detect_shell()

    config_map = {
        "fish": home / ".config" / "fish" / "config.fish",
        "bash": home / ".bashrc",
        "zsh": home / ".zshrc",
    }

    return config_map.get(shell)


def ensure_path_in_shell_config(path: str = "~/.local/bin") -> bool:
    """Ensure a path is in the user's shell config."""
    config_file = get_shell_config_file()
    if not config_file:
        logger.debug(f"No config file for shell: {detect_shell()}")
        return False

    shell = detect_shell()
    expanded_path = str(Path(path).expanduser())

    try:
        if not config_file.exists():
            config_file.parent.mkdir(parents=True, exist_ok=True)
            config_file.touch()

        content = config_file.read_text()

        if shell == "fish":
            path_line = f"fish_add_path {expanded_path}"
            if path_line in content:
                return True

            # Add to fish config
            marker = "# Added by Volume Monitor installer"
            if marker not in content:
                content += f"\n\n{marker}\n{path_line}\n"
                config_file.write_text(content)
                return True
        else:
            # POSIX shells (bash, zsh)
            export_line = f'export PATH="{expanded_path}:$PATH"'
            if export_line in content:
                return True

            marker = "# Added by Volume Monitor installer"
            if marker not in content:
                content += f"\n\n{marker}\n{export_line}\n"
                config_file.write_text(content)
                return True

    except Exception as e:
        logger.error(f"Failed to update shell config: {e}")

    return False


def generate_fish_completions() -> Optional[str]:
    """Generate Fish shell completion script for volume-monitor."""
    if not is_fish_shell():
        return None

    return '''
# Fish completions for volume-monitor
# Generated by Volume Monitor installer

function __fish_volume_monitor_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

complete -c volume-monitor -f

# Main options
complete -c volume-monitor -s s -l start -d 'Start monitor in background'
complete -c volume-monitor -s f -l start-foreground -d 'Start monitor in foreground'
complete -c volume-monitor -s k -l stop -d 'Stop running monitor'
complete -c volume-monitor -s r -l restart -d 'Restart the monitor'
complete -c volume-monitor -s S -l status -d 'Check if monitor is running'
complete -c volume-monitor -s d -l debug -d 'Enable verbose debug logging'
complete -c volume-monitor -s c -l configure -d 'Run configuration wizard'
complete -c volume-monitor -s t -l toggle -d 'Toggle audio output device'
complete -c volume-monitor -s l -l list-devices -d 'List audio output devices'
complete -c volume-monitor -l list-streams -d 'List per-app audio streams'
complete -c volume-monitor -s h -l help -d 'Show help message'

# Device management
complete -c volume-monitor -s i -l include -d 'Add device to toggle list' -x
complete -c volume-monitor -s x -l exclude -d 'Remove device from toggle list' -x
complete -c volume-monitor -s R -l reset-devices -d 'Clear device filter list'
'''


def install_fish_completions() -> bool:
    """Install Fish shell completions for volume-monitor."""
    if not is_fish_shell():
        return False

    completions_dir = Path.home() / ".config" / "fish" / "completions"

    try:
        completions_dir.mkdir(parents=True, exist_ok=True)
        completion_file = completions_dir / "volume-monitor.fish"

        completions = generate_fish_completions()
        if completions:
            completion_file.write_text(completions)
            logger.info(f"Fish completions installed to {completion_file}")
            return True

    except Exception as e:
        logger.error(f"Failed to install fish completions: {e}")

    return False


def get_fish_install_instructions() -> str:
    """Get Fish-specific installation instructions."""
    return """
# Fish Shell Setup for Volume Monitor

## Add pipx to PATH (if not already done)
fish_add_path ~/.local/bin

# Or add to ~/.config/fish/config.fish:
echo 'fish_add_path ~/.local/bin' >> ~/.config/fish/config.fish

## Useful aliases (add to config.fish)
alias vm='volume-monitor'
alias vms='volume-monitor --status'
alias vml='volume-monitor --list-devices'
alias vmt='volume-monitor --toggle'
alias vmc='volume-monitor --configure'

## Reload fish config
source ~/.config/fish/config.fish
# Or restart your terminal

## Install Volume Monitor
cd volume-monitor
fish install.fish
"""
