#!/bin/bash
# Generate Fish shell completions from argparse

# This script extracts the argument parser and generates fish completions

cat > ~/.config/fish/completions/volume-monitor.fish << 'FISHEOF'
# Fish completions for volume-monitor
# Auto-generated by generate-fish-completions.sh

function __fish_volume_monitor_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __fish_volume_monitor_using_command
    set -l cmd (commandline -opc)
    set -l subcommands start stop restart status configure
    for sub in $subcommands
        if contains -- $sub $cmd
            return 0
        end
    end
    return 1
end

# Disable file completion by default
complete -c volume-monitor -f

# Main commands
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s s -l start -d 'Start monitor in background'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s f -l start-foreground -d 'Start monitor in foreground'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s k -l stop -d 'Stop running monitor'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s r -l restart -d 'Restart the monitor'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s S -l status -d 'Check if monitor is running'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s d -l debug -d 'Enable verbose debug logging'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s c -l configure -d 'Run configuration wizard'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s t -l toggle -d 'Toggle audio output device'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s l -l list-devices -d 'List audio output devices'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -l list-streams -d 'List per-app audio streams'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s h -l help -d 'Show help message'

# Device management options
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s i -l include -d 'Add device to toggle list' -x -a '(__fish_volume_monitor_devices)'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s x -l exclude -d 'Remove device from toggle list' -x -a '(__fish_volume_monitor_devices)'
complete -c volume-monitor -n '__fish_volume_monitor_needs_command' -s R -l reset-devices -d 'Clear device filter list'

# Helper function to list audio devices
function __fish_volume_monitor_devices
    wpctl status 2>/dev/null | grep -A 20 "Sinks:" | grep "^\s\+[0-9]" | string match -rg '\d+\.\s+(.+)' | string trim
end
FISHEOF

echo "Fish completions generated at ~/.config/fish/completions/volume-monitor.fish"